---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: static/stories
  label: Acualités
  create: all
  match: "**/*"
  templates:
  - storie
- type: directory
  path: static/events
  label: Événements
  create: all
  match: "**/*"
  templates:
  - event
- type: directory
  path: static/pages
  label: Pages
  create: all
  match: "**/*"
  templates:
  - page
- type: directory
  path: static/blocks
  label: Blocs
  create: all
  match: "**/*"
  templates:
  - block
- type: heading
  label: Configuration
- type: document
  path: static/configuration/settings.json
  label: Paramètres
upload_dir: static/files
public_path: "/files"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  instant_preview_command: npm run forestry:preview
