---
label: Paramètres des évenements
hide_body: true
fields:
- name: events
  type: field_group
  config: {}
  fields:
  - name: categories
    type: tag_list
    default: []
    label: Catégories
  label: Évenements
pages:
- static/settings/events.json
